//! # sentinel-guest
//!
//! The actual compiled Wasm agent that runs inside the SENTINEL sandbox.

wit_bindgen::generate!({
    path: "../wit/sentinel.wit",
    world: "sentinel-guest",
});

use sentinel::agent::capabilities::*;
use sentinel::agent::hitl::*;
use sentinel::agent::logging::*;
use sentinel::agent::reasoning::*;
struct Component;

impl Guest for Component {
    fn run(context_json: String) -> i32 {
        log(LogLevel::Info, "guest", &format!("Agent started with context: {}", context_json));

        // 1. Request capabilities
        let justify = "Need to read Cargo.toml to summarize its contents.";
        match request_fs_read("Cargo.toml", justify) {
            CapabilityResult::Granted(token) => {
                log(LogLevel::Info, "guest", &format!("Granted fs.read with token ID: {}", token.id));
                
                // 2. Read the file
                match fs_read(&token.id, "Cargo.toml") {
                    Ok(bytes) => {
                        let content = String::from_utf8_lossy(&bytes);
                        log(LogLevel::Info, "guest", &format!("File read successfully ({} bytes)", content.len()));
                        
                        // 3. Request LLM Completion
                        let messages = vec![
                            ChatMessage {
                                role: "system".to_string(),
                                content: "Summarize the given configuration file concisely.".to_string(),
                            },
                            ChatMessage {
                                role: "user".to_string(),
                                content: content.into_owned(),
                            }
                        ];
                        
                        match complete(&messages, Some(500), Some(0.7), None) {
                            Ok(resp) => {
                                log(LogLevel::Info, "guest", &format!("LLM Summary generated by {}: {}", resp.model, resp.content));
                                log(LogLevel::Info, "guest", "Agent finished successfully.");
                            }
                            Err(e) => {
                                log(LogLevel::Error, "guest", &format!("LLM error: {}", e));
                                return 1;
                            }
                        }
                    }
                    Err(e) => {
                        log(LogLevel::Error, "guest", &format!("Failed to read file: {}", e));
                        return 1;
                    }
                }
            }
            CapabilityResult::Denied(reason) => {
                log(LogLevel::Error, "guest", &format!("Access denied for fs.read: {}", reason));
                return 1;
            }
        }
        
        0
    }

    fn handle_event(event_type: String, payload_json: String) -> String {
        log(LogLevel::Info, "guest", &format!("Received event {} with payload {}", event_type, payload_json));
        String::new()
    }
}

export!(Component);
